In [4]:
# 1. 要素が 0 の一次元配列（長さ10）を作る
import numpy as np    # NumPyライブラリをインポート
nzeros = np.zeros(10)
print(nzeros)


# 2. 要素がすべて 1 の配列（長さ5）を作る
nones = np.ones(5)
print(nones)


# 3. 1から10までの整数が順番に入った配列を作る
ten_arrs = np.arange(1, 11)
print(ten_arrs)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#4. 1番の配列 の5番目の要素を100に変更
# nzeros =  0 の一次元配列（長さ10）
nzeros[4] = 100  # インデックス4（5番目の要素）に100を代入
print(nzeros)


# 5. 3番の配列（1〜10）を逆順にする
# ten_arrs = 1から10までの整数が順番に入った配列
ten_reverse = ten_arrs[::-1]
print(ten_reverse)


[  0.   0.   0.   0. 100.   0.   0.   0.   0.   0.]
[10  9  8  7  6  5  4  3  2  1]


In [7]:
# 6. 配列 [1, 2, 3] を3×3の行列に変換
multi_array = np.array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])  #  [1, 2, 3]は1行分の一次元配列データ
print(multi_array)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
# 7. [1, 2, 3] と [4, 5, 6] の要素ごとの和
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c_sum = a + b
print(c_sum)

[5 7 9]


In [9]:
# 8. 3×3のランダム行列の各行の平均
nums = np.random.randint(1,10,(3,3))
print(f"{nums}\n")

nums_ave = np.mean(nums, axis = 1)    # np.meanで平均値 を計算。axis=1 は「行ごとに計算する」という意味
print(nums_ave)

[[7 8 9]
 [5 5 8]
 [6 9 1]]

[8.         6.         5.33333333]


In [10]:
# 9. 1から9の整数を含む3×3の行列を転置(メソッドがあります)
arrs = np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arrs_t = arrs.T   # arrs.T は 行と列を入れ替えた配列（転置）にする
arrs_t

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])